name: Deploy to Prod and Push to Databricks

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'yes' to confirm deployment to production"
        required: true
        default: "no"

jobs:
  deploy:
    if: ${{ github.ref == 'refs/heads/prod' && github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout prod branch
      - name: Checkout prod branch
        uses: actions/checkout@v3
        with:
          ref: prod

      # Step 2: Configure Git User
      - name: Configure Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      # Step 3: Fetch all branches to ensure they are available
      - name: Fetch all branches
        run: git fetch --all

      # Step 4: Check out main branch and merge into prod
      - name: Check out and merge main into prod
        run: |
          git checkout main
          git checkout prod
          git merge main --allow-unrelated-histories -m "Manual deployment from main to prod"

      # Step 5: Remove any existing origin and re-add with PAT
      - name: Add remote with PAT
        run: |
          git remote remove origin || true
          git remote add origin https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/arvindarrives25/dev_project.git

      # Step 6: Push to prod branch using explicit remote and branch
      - name: Push to prod branch
        run: |
          git push origin prod
