name: Deploy to Prod and Push to Databricks

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'yes' to confirm deployment to production"
        required: true
        default: "no"

jobs:
  deploy:
    if: ${{ github.event.inputs.confirmation == 'yes' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Check out prod branch
        run: git checkout prod

      - name: Merge dev into prod
        run: git merge origin/dev -m "Manual deployment from dev to prod"

      - name: Push to prod branch
        run: git push origin prod

      # Deploy to Azure Databricks using Databricks CLI
      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: "https://<your-databricks-instance>.azuredatabricks.net"  # Update with your Databricks URL
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks configure --token <<< "${DATABRICKS_HOST}\n${DATABRICKS_TOKEN}"

      - name: Upload Notebooks to Databricks
        run: |
          databricks workspace import_dir . /Repos/prod_project --overwrite
