name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: "Type 'yes' to confirm deployment to production"
        required: true
        default: "no"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout prod branch
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Set up Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge main into prod
        run: |
          git fetch origin main
          git checkout prod
          git merge origin/main -m "Manual deployment from main to prod"

      - name: Push to prod using PAT
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git remote remove origin || true
          git remote add origin https://x-access-token:${TOKEN}@github.com/arvindarrives25/dev_project.git
          git push origin prod
